name: main

on:
  pull_request:
  push:
  schedule:
    # Prime the caches every Monday
    - cron: 0 1 * * MON

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        ocaml-compiler:
          - 4.12.0+domains
          - 4.12.0+domains+effects

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get latest Multicore commit hash
        id: multicore_hash
        shell: bash
        run: |
          curl -sH "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/ocaml-multicore/ocaml-multicore/commits/4.12+domains+effects \
          | jq .commit.tree.sha | xargs printf '::set-output name=commit::%s'

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ocaml-variants.${{ matrix.ocaml-compiler }}
          opam-repositories: |
            multicore: https://github.com/ocaml-multicore/multicore-opam.git
            default: https://github.com/ocaml/opam-repository.git
          cache-prefix: ${{ steps.multicore_hash.outputs.commit }}

      - run: opam install . --deps-only --with-test

      - run: opam exec -- make all

      - run: opam exec -- make run_test
