name: main

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - name: linux
            os: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run the CI
        run: |
          bash -xe .ci.sh
